name: Build LiTr Demo App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.cache/gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - run: gradle build
      - uses: actions/upload-artifact@v2
        with:
          path: build/outputs/apk
          name: litr-demo-app.apk
